version: '2'

services:
  iote2e-mysql-master:
    image: mysql:5.6
    command: mysqld_safe
    hostname: iiote2e-mysql-master
    container_name: iote2e-mysql-master
    mem_limit: 8g
    memswap_limit: 8g
    networks:
      default:
        ipv4_address: 192.168.21.60
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - ../../iote2e-shared:/tmp/iote2e-shared

networks:
  default:
    external:
      name: iote2enet