version: '2'

services:
  iote2e-cassandra1:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra1.yaml
    hostname: iote2e-cassandra1
    container_name: iote2e-cassandra1
    mem_limit: 16g
    memswap_limit: 16g
    networks:
      default:
        ipv4_address: 192.168.21.91
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9041:9042
    volumes:
      - ./conf:/conf
      - ./data:/tmp/data
      
  iote2e-cassandra2:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra2.yaml
    hostname: iote2e-cassandra2
    container_name: iote2e-cassandra2
    mem_limit: 16g
    memswap_limit: 16g
    networks:
      default:
        ipv4_address: 192.168.21.92
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9042:9042
    volumes:
      - ./conf:/conf
      - ./data:/tmp/data
    
  iote2e-cassandra3:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra3.yaml
    hostname: iote2e-cassandra3
    container_name: iote2e-cassandra3
    mem_limit: 16g
    memswap_limit: 16g
    networks:
      default:
        ipv4_address: 192.168.21.93
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
     - 9043:9042
    volumes:
      - ./conf:/conf
      - ./data:/tmp/data
      
  iote2e-cassandra4:
    image: cassandra:3.9
    command: cassandra -f -R -Dcassandra.config=file:///conf/cassandra4.yaml
    hostname: iote2e-cassandra4
    container_name: iote2e-cassandra4
    mem_limit: 16g
    memswap_limit: 16g
    networks:
      default:
        ipv4_address: 192.168.21.94
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    ports:
      - 9044:9042
    volumes:
      - ./conf:/conf
      - ./data:/tmp/data
  
networks:
  default:
    external:
      name: iote2enet